(function registerLegendsMap() {
  const legends = [
    { name: 'GO', color: null },
    { name: 'Osaka Bay', color: 'japan' },
    { name: 'Festival Fund', color: null },
    { name: 'Shibuya Crossing', color: 'japan' },
    { name: 'Cultural Tax', color: null },
    { name: 'Shinkansen Rail', color: 'railroad' },
    { name: 'Valencia Harbor', color: 'spain' },
    { name: 'Discovery', color: null },
    { name: 'Seville Plaza', color: 'spain' },
    { name: 'Bilbao Docks', color: 'spain' },
    { name: 'Harbor Detention', color: null },
    { name: 'Vancouver Quay', color: 'canada' },
    { name: 'Niagara Energy', color: 'utility' },
    { name: 'Toronto Market', color: 'canada' },
    { name: 'Montreal Mile', color: 'canada' },
    { name: 'Polar Express Rail', color: 'railroad' },
    { name: 'Delhi Bazaar', color: 'india' },
    { name: 'Heritage Chest', color: null },
    { name: 'Jaipur Gates', color: 'india' },
    { name: 'Kochi Port', color: 'india' },
    { name: 'Safari Rest Stop', color: null },
    { name: 'Sydney Harbour', color: 'australia' },
    { name: 'Discovery', color: null },
    { name: 'Brisbane Bay', color: 'australia' },
    { name: 'Perth Outback', color: 'australia' },
    { name: 'Coral Coast Rail', color: 'railroad' },
    { name: 'Oaxaca Street', color: 'mexico' },
    { name: 'Cancun Shore', color: 'mexico' },
    { name: 'Maya Utilities', color: 'utility' },
    { name: 'Tulum Ruins', color: 'mexico' },
    { name: 'Go To Jail', color: null },
    { name: 'Cape Town Ridge', color: 'southafrica' },
    { name: 'Durban Market', color: 'southafrica' },
    { name: 'Heritage Fund', color: null },
    { name: 'Pretoria Square', color: 'southafrica' },
    { name: 'Savannah Rail', color: 'railroad' },
    { name: 'Discovery', color: null },
    { name: 'Stockholm Quay', color: 'sweden' },
    { name: 'Fjord Tax', color: null },
    { name: 'Gothenburg Pier', color: 'sweden' },
  ];

  window.MonopolyMaps = window.MonopolyMaps || {};
  window.MonopolyMaps.legends = legends;
})();
