(function registerWorldMap() {
  const world = [
    { name: 'GO', color: null },
    { name: 'Vaikalmedu', color: 'brazil' },
    { name: 'Pudhaiyal', color: null },
    { name: 'Thopupalayam', color: 'brazil' },
    { name: 'Varumana vari', color: null },
    { name: 'Vettaiyan Airways', color: 'railroad' },
    { name: 'Paramathi', color: 'israel' },
    { name: 'Surprise', color: null },
    { name: 'P Velur', color: 'israel' },
    { name: 'Kabilarmalai', color: 'israel' },
    { name: 'Jail', color: null },
    { name: 'Velarivelli', color: 'italy' },
    { name: 'U K Consultancy', color: 'utility' },
    { name: 'Boat Theeru', color: 'italy' },
    { name: 'Polampatti', color: 'italy' },
    { name: 'Eagle Tractors', color: 'railroad' },
    { name: 'Karur', color: 'germany' },
    { name: 'Pudhaiyal', color: null },
    { name: 'Namakkal main', color: 'germany' },
    { name: 'Erode', color: 'germany' },
    { name: 'Vacation', color: null },
    { name: 'Pollachi', color: 'china' },
    { name: 'Surprise', color: null },
    { name: 'Paladdam', color: 'china' },
    { name: 'Udumalpet', color: 'china' },
    { name: 'Vettaiyan waterways', color: 'railroad' },
    { name: 'Unjalur', color: 'france' },
    { name: 'Noyal', color: 'france' },
    { name: 'Kathirvel vathukadai', color: 'utility' },
    { name: 'Kodumudi', color: 'france' },
    { name: 'Go To Jail', color: null },
    { name: 'Sala Palayam', color: 'uk' },
    { name: 'Govindham Palyam', color: 'uk' },
    { name: 'Pudhaiyal', color: null },
    { name: 'Valaiyal Karan Pudhur', color: 'uk' },
    { name: 'Vettaiyan Roadways', color: 'railroad' },
    { name: 'Surprise', color: null },
    { name: 'Mettur Dam', color: 'usa' },
    { name: 'Aadambara Vari', color: null },
    { name: 'Kolathur Beach', color: 'usa' },
  ];

  window.MonopolyMaps = window.MonopolyMaps || {};
  window.MonopolyMaps.world = world;
})();
